"""Stage 2: Contract test — synthesis section passes through engram trace correctly.

Verifies:
1. build_prompt_trace() assigns origin="synthesis" to the Procedural Rules section
2. synthesis rules appear in EvidenceTrace list
3. token_accounting.per_origin_used contains "synthesis" key when rules matched
4. engram_adapter passes sections through generically (origin flows unchanged)

Run from engram/ root:
    PYTHONPATH=. python tests/harness/test_synthesis_inspector_passthrough.py

Author: Jeffrey Dean
"""

import sys
import tempfile
import time
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from engram.memory.semantic_memory import SemanticMemory
from engram.memory.synthesis import SynthesisRule


class _TestRunner:
    def __init__(self):
        self.passed = 0; self.failed = 0; self.errors = []

    def run(self, name, fn):
        try:
            fn(); self.passed += 1; print(f"  PASS  {name}")
        except AssertionError as e:
            self.failed += 1; msg = f"  FAIL  {name}: {e}"; self.errors.append(msg); print(msg)
        except Exception as e:
            self.failed += 1
            msg = f"  ERROR {name}: {type(e).__name__}: {e}"
            self.errors.append(msg); print(msg)

    def summary(self):
        total = self.passed + self.failed
        print(f"\n{'=' * 60}")
        print(f"Results: {self.passed}/{total} passed")
        if self.errors:
            for e in self.errors: print(e)
        return self.failed == 0


def _write_rule(sm: SemanticMemory, rule_text: str, support: list,
               confidence: float = 0.85, project_id: str = "test") -> str:
    rule = SynthesisRule(
        rule_text=rule_text,
        support_episode_ids=support,
        support_count=len(support),
        confidence=confidence,
    )
    payload = rule.to_payload(project_id)
    sm.store_synthesis_rule(payload, project_id=project_id)
    return payload["id"]


# --- Tests -------------------------------------------------------------------

def test_title_to_origin_includes_synthesis():
    """Procedural Rules section must get origin='synthesis' in build_prompt_trace."""
    from engram.project_memory import ProjectMemory

    with tempfile.TemporaryDirectory() as td:
        sm = SemanticMemory(db_path=Path(td))
        _write_rule(sm, "Always use WAL mode on SQLite connections",
                    support=["ep_a", "ep_b", "ep_c"])

        # Inject a mock build_prompt that produces a Procedural Rules section
        mock_result = {
            "prompt": (
                "## Episodic\nSome episodic content.\n\n"
                "## Procedural Rules\n- Always use WAL mode on SQLite connections\n\n"
                "## User\nHow do I configure SQLite?"
            ),
            "prompt_tokens": 50,
            "context": None,
            "compressed": False,
            "memory_tokens": 20,
        }

        # Build a minimal PM with our SemanticMemory injected
        pm = ProjectMemory.__new__(ProjectMemory)
        pm.project_id = "test"
        pm.semantic = sm
        pm.budget = SimpleNamespace(total_prompt_tokens=4096)
        pm._token_counter = lambda t: max(1, len(t) // 4)
        pm.session_id = "sess"

        # Patch build_prompt to return our controlled output
        with patch.object(pm, "build_prompt", return_value=mock_result):
            with patch.object(pm, "_build_synthesis_block",
                              return_value="- Always use WAL mode on SQLite connections"):
                from engram.inspection import PromptBuildTrace
                trace = pm.build_prompt_trace.__func__(
                    pm,
                    "How do I configure SQLite?",
                    _result=mock_result,
                )

        # The Procedural Rules section must have origin="synthesis"
        origins = {s.origin for s in trace.sections}
        assert "synthesis" in origins, \
            f"'synthesis' origin missing from sections. Got: {origins}"

        # Must NOT have "procedural_rules" as autogenerated fallback
        assert "procedural_rules" not in origins, \
            f"'procedural_rules' fallback found — title_to_origin mapping is wrong"


def test_synthesis_evidence_items():
    """Rules from synthesis block should appear as EvidenceTrace with source='synthesis'."""
    from engram.project_memory import ProjectMemory

    with tempfile.TemporaryDirectory() as td:
        sm = SemanticMemory(db_path=Path(td))
        _write_rule(sm, "Set WAL mode on every SQLite connection",
                    support=["ep_a", "ep_b", "ep_c"])

        mock_result = {
            "prompt": (
                "## Episodic\nSome content.\n\n"
                "## Procedural Rules\n- Set WAL mode on every SQLite connection\n\n"
                "## User\nSQLite config?"
            ),
            "prompt_tokens": 40,
            "context": None,
            "compressed": False,
            "memory_tokens": 15,
        }

        pm = ProjectMemory.__new__(ProjectMemory)
        pm.project_id = "test"
        pm.semantic = sm
        pm.budget = SimpleNamespace(total_prompt_tokens=4096)
        pm._token_counter = lambda t: max(1, len(t) // 4)
        pm.session_id = "sess"

        with patch.object(pm, "build_prompt", return_value=mock_result):
            with patch.object(pm, "_build_synthesis_block",
                              return_value="- Set WAL mode on every SQLite connection"):
                trace = pm.build_prompt_trace.__func__(pm, "SQLite config?", _result=mock_result)

        synth_evidence = [e for e in trace.evidence if e.source == "synthesis"]
        assert len(synth_evidence) >= 1, \
            f"No synthesis evidence items found. Evidence sources: {[e.source for e in trace.evidence]}"
        assert "WAL" in synth_evidence[0].text, \
            f"Expected WAL rule in evidence, got: {synth_evidence[0].text}"


def test_token_accounting_synthesis_key():
    """per_origin_used must include 'synthesis' key when synthesis section is present."""
    from engram.project_memory import ProjectMemory

    with tempfile.TemporaryDirectory() as td:
        sm = SemanticMemory(db_path=Path(td))
        _write_rule(sm, "Prefer async coroutines for IO-bound tasks",
                    support=["ep_a", "ep_b", "ep_c"])

        mock_result = {
            "prompt": (
                "## Procedural Rules\n- Prefer async coroutines for IO-bound tasks\n\n"
                "## User\nHow should I handle async IO?"
            ),
            "prompt_tokens": 30,
            "context": None,
            "compressed": False,
            "memory_tokens": 10,
        }

        pm = ProjectMemory.__new__(ProjectMemory)
        pm.project_id = "test"
        pm.semantic = sm
        pm.budget = SimpleNamespace(total_prompt_tokens=4096)
        pm._token_counter = lambda t: max(1, len(t) // 4)
        pm.session_id = "sess"

        with patch.object(pm, "build_prompt", return_value=mock_result):
            with patch.object(pm, "_build_synthesis_block",
                              return_value="- Prefer async coroutines for IO-bound tasks"):
                trace = pm.build_prompt_trace.__func__(pm, "async IO?", _result=mock_result)

        assert "synthesis" in trace.token_accounting.per_origin_used, \
            f"'synthesis' missing from per_origin_used. Keys: {list(trace.token_accounting.per_origin_used)}"
        assert trace.token_accounting.per_origin_used["synthesis"] > 0, \
            "synthesis token count should be > 0"


def test_no_synthesis_section_when_no_rules():
    """When synthesis block is empty, no synthesis section or evidence should appear."""
    from engram.project_memory import ProjectMemory

    mock_result = {
        "prompt": "## Episodic\nSome content.\n\n## User\nA query.",
        "prompt_tokens": 20,
        "context": None,
        "compressed": False,
        "memory_tokens": 10,
    }

    with tempfile.TemporaryDirectory() as td:
        sm = SemanticMemory(db_path=Path(td))  # empty — no rules

        pm = ProjectMemory.__new__(ProjectMemory)
        pm.project_id = "test"
        pm.semantic = sm
        pm.budget = SimpleNamespace(total_prompt_tokens=4096)
        pm._token_counter = lambda t: max(1, len(t) // 4)
        pm.session_id = "sess"

        with patch.object(pm, "build_prompt", return_value=mock_result):
            with patch.object(pm, "_build_synthesis_block", return_value=""):
                trace = pm.build_prompt_trace.__func__(pm, "A query.", _result=mock_result)

        origins = {s.origin for s in trace.sections}
        assert "synthesis" not in origins, \
            f"synthesis section appeared but no rules exist: {origins}"
        synth_ev = [e for e in trace.evidence if e.source == "synthesis"]
        assert len(synth_ev) == 0, \
            f"synthesis evidence appeared but no rules exist: {synth_ev}"
        assert "synthesis" not in trace.token_accounting.per_origin_used, \
            "synthesis token accounting should be absent when no rules"


def test_adapter_section_passthrough():
    """Inspector adapter must pass origin='synthesis' through unchanged."""
    # Test the mapping in _trace_to_inspector_trace directly
    try:
        from llm_inspector.adapters.engram_adapter import _trace_to_inspector_trace
        from llm_inspector.protocols import AugmentRequest
        from llm_inspector.core.types import Turn
        from engram_lite.inspection import (
            PromptBuildTrace, PromptSectionTrace, TokenAccountingTrace
        )
    except ImportError as e:
        print(f"  SKIP  test_adapter_section_passthrough: {e}")
        return

    # Build a minimal trace with a synthesis section
    synth_section = PromptSectionTrace(
        title="Procedural Rules",
        origin="synthesis",
        text="- Use WAL mode always",
        tokens=5,
    )
    user_section = PromptSectionTrace(
        title="User",
        origin="user",
        text="SQLite config?",
        tokens=3,
    )
    trace_obj = PromptBuildTrace(
        sections=[synth_section, user_section],
        evidence=[],
        token_accounting=TokenAccountingTrace(per_origin_used={"synthesis": 5, "user": 3}),
        flags={},
        final_prompt="",
    )

    req = AugmentRequest(
        turn=Turn(role="user", text="SQLite config?", session_id="s1"),
        session_id="s1",
    )
    inspector_trace = _trace_to_inspector_trace(req, trace_obj)

    # Origin must survive the adapter mapping
    origins = {s.origin for s in inspector_trace.context.sections}
    assert "synthesis" in origins, \
        f"'synthesis' origin lost in adapter passthrough. Got: {origins}"
    assert inspector_trace.context.token_accounting.per_origin_used.get("synthesis") == 5, \
        "synthesis token count not preserved by adapter"


# --- Main --------------------------------------------------------------------

def main():
    runner = __TestRunner()
    print("Synthesis inspector passthrough tests")
    print("=" * 60)
    print("\n[engram trace]")
    runner.run("test_title_to_origin_includes_synthesis",
               test_title_to_origin_includes_synthesis)
    runner.run("test_synthesis_evidence_items", test_synthesis_evidence_items)
    runner.run("test_token_accounting_synthesis_key",
               test_token_accounting_synthesis_key)
    runner.run("test_no_synthesis_section_when_no_rules",
               test_no_synthesis_section_when_no_rules)
    print("\n[inspector adapter]")
    runner.run("test_adapter_section_passthrough", test_adapter_section_passthrough)
    return 0 if runner.summary() else 1


if __name__ == "__main__":
    sys.exit(main())
